### ISSUE TITLE
If .md file not present fallback to html file

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion-markdown-extension#7]
Would it possible for the MarkdownExtension to search for <spec>.md and then <spec>.html if markdown file not found.   

This way I could specify the use of the extension in the base class and not worry about updating every fixture where I convert the specification over to markdown.

**Comment by nigelcharman** [comment]
Fixed in Concordion [2.0.0-SNAPSHOT](https://github.com/concordion/concordion/releases/tag/2.0.0-SNAPSHOT-20160125).
