### ISSUE TITLE
List Items in Examples

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion-markdown-extension#8]
# Issue 1

```
## [An Example](- "example1")
Given I want to add a list item in an example I will use:

* list item failing
```

The test fails with error:

```
[Fatal Error] :12:13: The element type "li" must be terminated by the matching end-tag "</li>".
```
# Issue 2

```
## [An Example](- "example1")
Given I want to add a list item in an example I will use:
* list item puts star
* list item puts star
```

Treats as a normal character in a sentence - so displays star rather than black circle and wrapped lines are not indented

**Comment by nigelcharman** [comment]
I've created a fix for Issue 1. It's a bit of a strange one - in the AST we're getting a RootNode under the list item, so we think the closing root node is the end of file and add a closing </div> to close the example while we're still processing the list item.

**Comment by nigelcharman** [comment]
For issue 2, I assume you've add the Pegdown extension to use the Github Flavored Markdown style hard wraps?

If so, I suspect it is an issue with the underlying Pegdown parser. Please raise as a separate issue. If possible, try it with Pegdown without the Concordion Markdown extension, and raise an issue on the Pegdown project if it fails.
